name: Terraform Lint

on:
  push:

  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: terraform-linters/setup-tflint@v4

      - name: Initialise TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive
