name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Display Release Information

        run: |

          echo "Release published."

          echo "${{ github.event.release.tag_name }}"
