name: Terraform Security

on:
  push:

  pull_request:

permissions:
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov

        uses: bridgecrewio/checkov-action@master

        with:
          directory: .
          framework: terraform
